[package]
name = "svalin_iced"
version = "0.1.0"
edition = "2024"

[dependencies]

svalin.workspace = true
svalin_pki.workspace = true
svalin_rpc.workspace = true
svalin_sysctl.workspace = true
svalin_store.workspace = true

# frozen_term = { git = "https://github.com/Rahn-IT/frostbyte_terminal.git"}
# async_pty = { git = "https://github.com/Rahn-IT/frostbyte_terminal.git" }

iced = { git = "https://github.com/iced-rs/iced.git", features = [
    "canvas",
    "wgpu",
    "tokio",
    "advanced",
    "image",
    "sipper"
] }
iced_core = { git = "https://github.com/iced-rs/iced.git" }
# iced = { version = "^0.14.0", features = [
#     "canvas",
#     "wgpu",
#     "tokio",
#     "advanced",
#     "image",
#     "sipper"
# ] }
anyhow = "1.0.104"
futures-util = "0.3.34"
tokio.workspace = true
totp-rs = { workspace = true }
lyon_algorithms = "1.0.21"
thiserror.workspace = true
tokio-stream = { version = "0.1.19", features = ["full"] }
tokio-util.workspace = true
futures = "0.3.34"
uuid = "1.26.0"
rust-i18n = "4.2.1"
tracing.workspace = true
iced_fonts = { git = "https://git.redhawkcodes.dev/redhawk18/iced_fonts.git", branch = "master" }
chrono = "0.4.45"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
rfd = "0.17.2"

[build-dependencies]
iced_fontello = {git = "https://github.com/hecrj/iced_fontello.git"}
