[package]
name = "svalin_sysctl"
version.workspace = true
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
portable-pty.workspace = true
sysinfo = { workspace = true, features = ["serde"] }
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true

[target.'cfg(windows)'.dependencies]
windows-registry = "0.6.1"
