name: Cargo Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  Cargo-Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: cargo test
      run: cargo test