name: Cargo Test
on:
  push:
    branches:
      - master
      - renovate/*

jobs:
  Cargo-Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: cargo test
      run: cargo test

  Flutter-Build-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gui_flutter
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Set Up Java
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: add jq
      run: apt-get update && apt-get install -y jq clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 
    - name: fix weird git behaviour
      run: git config --global --add safe.directory "/opt/hostedtoolcache/flutter/*"
    - name: install flutter dependencies
      run: flutter pub get
    - uses: taiki-e/install-action@cargo-llvm-cov
    - name: build
      run: flutter build linux