name: Cargo Test
on:
  push:
    branches:
      - master
      - renovate/*

jobs:
  Cargo-Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/      
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
    - name: cargo test
      run: cargo test

  Flutter-Build-Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gui_flutter
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/      
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: install rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Set Up Java
      uses: actions/setup-java@v3.12.0
      with:
        distribution: 'oracle'
        java-version: '17'
    - name: add jq
      run: apt-get update && apt-get install -y jq clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev
    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable' 
    - name: install dependencies
      run: git config --global --add safe.directory /opt/hostedtoolcache/flutter/* && flutter pub get && cargo install 'flutter_rust_bridge_codegen@^2.0.0-dev.0'
    - name: debug rust install
      run: ls -la $HOME/.cargo/bin
    - name: build
      run: mkdir -p lib/src/rust && $HOME/.cargo/bin/flutter_rust_bridge_codegen generate && flutter build linux