// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Certificate>>
abstract class Certificate implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeStatusReceiver>>
abstract class RealtimeStatusReceiver implements RustOpaqueInterface {
  Future<void> changed();

  Future<RemoteLiveDataRealtimeStatus> currentOwned();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RecvError>>
abstract class RecvError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RemoteLiveData < RealtimeStatus >>>
abstract class RemoteLiveDataRealtimeStatus implements RustOpaqueInterface {
  RealtimeStatus? getReady();

  bool isPending();

  bool isUnavailable();
}

class AgentListItem {
  final PublicAgentData publicData;
  final bool onlineStatus;

  const AgentListItem({
    required this.publicData,
    required this.onlineStatus,
  });

  @override
  int get hashCode => publicData.hashCode ^ onlineStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentListItem &&
          runtimeType == other.runtimeType &&
          publicData == other.publicData &&
          onlineStatus == other.onlineStatus;
}

class CoreStatus {
  final double load;
  final BigInt frequency;

  const CoreStatus({
    required this.load,
    required this.frequency,
  });

  @override
  int get hashCode => load.hashCode ^ frequency.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoreStatus &&
          runtimeType == other.runtimeType &&
          load == other.load &&
          frequency == other.frequency;
}

class CpuStatus {
  final List<CoreStatus> cores;

  const CpuStatus({
    required this.cores,
  });

  @override
  int get hashCode => cores.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CpuStatus &&
          runtimeType == other.runtimeType &&
          cores == other.cores;
}

class MemoryStatus {
  final BigInt total;
  final BigInt available;
  final BigInt free;
  final BigInt used;

  const MemoryStatus({
    required this.total,
    required this.available,
    required this.free,
    required this.used,
  });

  @override
  int get hashCode =>
      total.hashCode ^ available.hashCode ^ free.hashCode ^ used.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryStatus &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          available == other.available &&
          free == other.free &&
          used == other.used;
}

class PublicAgentData {
  final String name;
  final Certificate cert;

  const PublicAgentData({
    required this.name,
    required this.cert,
  });

  @override
  int get hashCode => name.hashCode ^ cert.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicAgentData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cert == other.cert;
}

class RealtimeStatus {
  final CpuStatus cpu;
  final MemoryStatus memory;
  final SwapStatus swap;

  const RealtimeStatus({
    required this.cpu,
    required this.memory,
    required this.swap,
  });

  @override
  int get hashCode => cpu.hashCode ^ memory.hashCode ^ swap.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RealtimeStatus &&
          runtimeType == other.runtimeType &&
          cpu == other.cpu &&
          memory == other.memory &&
          swap == other.swap;
}

class SwapStatus {
  final BigInt total;
  final BigInt free;
  final BigInt used;

  const SwapStatus({
    required this.total,
    required this.free,
    required this.used,
  });

  @override
  int get hashCode => total.hashCode ^ free.hashCode ^ used.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapStatus &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          free == other.free &&
          used == other.used;
}
