// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `CoreStatus`, `CpuStatus`, `_RemoteLiveDataRealtimeStatus`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Certificate>>
abstract class Certificate implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RealtimeStatusReceiver>>
abstract class RealtimeStatusReceiver implements RustOpaqueInterface {
  Future<RemoteLiveDataRealtimeStatus> currentOwned();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RemoteLiveData < RealtimeStatus >>>
abstract class RemoteLiveDataRealtimeStatus implements RustOpaqueInterface {
  Future<bool> isPending();
}

class AgentListItem {
  final PublicAgentData publicData;
  final bool onlineStatus;

  const AgentListItem({
    required this.publicData,
    required this.onlineStatus,
  });

  @override
  int get hashCode => publicData.hashCode ^ onlineStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AgentListItem &&
          runtimeType == other.runtimeType &&
          publicData == other.publicData &&
          onlineStatus == other.onlineStatus;
}

class PublicAgentData {
  final String name;
  final Certificate cert;

  const PublicAgentData({
    required this.name,
    required this.cert,
  });

  @override
  int get hashCode => name.hashCode ^ cert.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PublicAgentData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cert == other.cert;
}
