// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name, hint: hint);

Stream<String> streamTime({dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleStreamTime(hint: hint);

Future<Test> test({dynamic hint}) =>
    RustLib.instance.api.crateApiSimpleTest(hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HiddenType>>
@sealed
class HiddenType extends RustOpaque {
  HiddenType.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  HiddenType.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_HiddenType,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_HiddenType,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_HiddenTypePtr,
  );
}

@freezed
sealed class Test with _$Test {
  const Test._();

  const factory Test.a() = Test_A;
  const factory Test.b(
    int field0,
  ) = Test_B;
  const factory Test.c({
    required String name,
    required int age,
  }) = Test_C;
  const factory Test.d(
    HiddenType field0,
  ) = Test_D;
}
