// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Stream<String> streamTime() => RustLib.instance.api.crateApiSimpleStreamTime();

Future<Test> test() => RustLib.instance.api.crateApiSimpleTest();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HiddenType>>
abstract class HiddenType implements RustOpaqueInterface {}

@freezed
sealed class Test with _$Test {
  const Test._();

  const factory Test.a() = Test_A;
  const factory Test.b(
    int field0,
  ) = Test_B;
  const factory Test.c({
    required String name,
    required int age,
  }) = Test_C;
  const factory Test.d(
    HiddenType field0,
  ) = Test_D;
}
