// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.2.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<Device> deviceReceiverIntoStreamsink(
        {required ReceiverDevice receiver}) =>
    RustLib.instance.api
        .crateApiStreamsinkDeviceReceiverIntoStreamsink(receiver: receiver);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Receiver < Device >>>
abstract class ReceiverDevice implements RustOpaqueInterface {}
