// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.35.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'client.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// The type `Algorithm` is not used by any `pub` functions, thus it is ignored.
// The type `__external_impl__544f5450` is not used by any `pub` functions, thus it is ignored.

Future<Totp> newTotp({required String accountName, dynamic hint}) =>
    RustLib.instance.api
        .crateApiTotpNewTotp(accountName: accountName, hint: hint);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SystemTimeError>>
@sealed
class SystemTimeError extends RustOpaque {
  SystemTimeError.dcoDecode(List<dynamic> wire)
      : super.dcoDecode(wire, _kStaticData);

  SystemTimeError.sseDecode(int ptr, int externalSizeOnNative)
      : super.sseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_SystemTimeError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_SystemTimeError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_SystemTimeErrorPtr,
  );
}
